package sts.mod.api;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class BuildTokenEncoderTest {
	// Reference tokens generated by the site itself (the current builder).
	// Valley test build: Cinnamon Sapling (m) + God Tamer-1 (o), region 1.
	private static final String VALLEY_TOKEN = "v1_BuJegC_u6yE_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFkAAAAAA";
	// Same gear + two charms: Keter Core 1 Generalist + Nihilo Core 3 Generalist.
	private static final String CHARM_TOKEN =
		"v1_BuJegC_u6yE_AAAAAAAAAAAAAAAAAAAAAB1LZXQtcl9Db3JlLTEtRyxOaWgtb19Db3JlLTMtRwAAAAAAAAAAA2QAAAAA";

	@Test
	void encodesValleyBuildByteIdentically() {
		String token = BuildTokenEncoder.encode(
			List.of("Cinnamon Sapling", "God Tamer-1", "None", "None", "None", "None"),
			null,
			null,
			null,
			null,
			List.of(),
			List.of(),
			List.of(),
			new int[] { 100, 0, 0, 0, 0, 0, 1 }
		);
		assertEquals(VALLEY_TOKEN, token);
	}

	@Test
	void encodesCharmBuildByteIdentically() {
		String token = BuildTokenEncoder.encode(
			List.of("Cinnamon Sapling", "God Tamer-1", "None", "None", "None", "None"),
			"Ket-r_Core-1-G,Nih-o_Core-3-G",
			null,
			null,
			null,
			List.of(),
			List.of(),
			List.of(),
			null
		);
		assertEquals(CHARM_TOKEN, token);
	}

	@Test
	void encodesClassSkillsAndEnhancements() {
		String token = BuildTokenEncoder.encode(
			List.of("Cinnamon Sapling", "God Tamer-1", "None", "None", "None", "None"),
			null,
			null,
			"Cleric",
			"Paladin",
			List.of(new BuildTokenEncoder.Skill("DivineJustice", 2)),
			List.of(new BuildTokenEncoder.Skill("HolyJavelin", 1)),
			List.of("DivineJustice"),
			null
		);
		assertEquals(
			"v1_BuJegC_u6yE_AAAAAAAAAAAAAAAAAAAAAAAABkNsZXJpYwENRGl2aW5lSnVzdGljZQIAAAAAAANkB1BhbGFkaW4BC0hvbHlKYXZlbGluAQENRGl2aW5lSnVzdGljZQA",
			token
		);
	}

	@Test
	void encodesWithoutEnhancements() {
		String token = BuildTokenEncoder.encode(
			List.of("Cinnamon Sapling", "God Tamer-1", "None", "None", "None", "None"),
			null,
			null,
			"Cleric",
			"Paladin",
			List.of(new BuildTokenEncoder.Skill("DivineJustice", 2)),
			List.of(new BuildTokenEncoder.Skill("HolyJavelin", 1)),
			List.of(),
			null
		);
		assertEquals(
			"v1_BuJegC_u6yE_AAAAAAAAAAAAAAAAAAAAAAAABkNsZXJpYwENRGl2aW5lSnVzdGljZQIAAAAAAANkB1BhbGFkaW4BC0hvbHlKYXZlbGluAQAA",
			token
		);
	}

	@Test
	void encodesClassAndSkills() {
		String token = BuildTokenEncoder.encode(
			List.of("Cinnamon Sapling", "God Tamer-1", "None", "None", "None", "None"),
			null,
			"My build",
			"Cleric",
			"Paladin",
			List.of(new BuildTokenEncoder.Skill("DivineJustice", 4), new BuildTokenEncoder.Skill("HolyAura", 3)),
			List.of(new BuildTokenEncoder.Skill("HolyJavelin", 5)),
			List.of(),
			null
		);
		// Decodes back with the same data on the site side: known prefix +
		// deterministic base64url content, just make sure it round-trips the
		// shape (prefix + non-empty payload + no padding).
		org.junit.jupiter.api.Assertions.assertTrue(token.startsWith("v1_"));
		org.junit.jupiter.api.Assertions.assertFalse(token.endsWith("="));
	}

	@Test
	void emptySlotsHashToZero() {
		String token = BuildTokenEncoder.encode(
			List.of("None", "None", "None", "None", "None", "None"),
			null, null, null, null, List.of(), List.of(), List.of(), null
		);
		assertEquals("v1_BgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANkAAAAAA", token);
	}
}
